{
	'name': 'TRIP REQUEST MODULE',
    'summary' : "TRIP REQUEST MODULE",
	'description' : "TRIP REQUEST MODULE",
	'author' : "ISGEC IT",
	'license' : "AGPL-3",
	'website' : "www.isgec.com",
	'category' : 'Uncategorized',
	'version' : '12.0.1.0.0',
	'depends' : ['base','hr_module'],
	'data' : [
		     'security/groups.xml',
		     'data/sequence.xml',
	         'security/ir.model.access.csv',
			 'views/TrpModule_TravelRequisitionTable.xml',
			 'views/TrpModule_SanctionIDTable.xml',
			 'views/TrpModule_EstimateExpenseDetailsTable.xml',
			 'views/TrpModule_OtherAllowanceExpensesTable.xml',
			 'views/TrpModule_GroupsDetailsTable.xml',
			 'views/TrpModule_FcmBookedDetailsTable.xml',
			 'views/TrpModule_FcmCheckRecordTable.xml',
			 # 'views/TrpModule_SubmissionTable.xml',
			 # 'views/TrpModule_SubmissionReportTable.xml',
			 'security/security.xml',
	         ],
}
