from odoo import models, fields, api


class TrpModuleSubmissionTable(models.Model):
    _name = 'trpmodule.submissiontable'

    name = fields.Char('INVOICE NO', required=True)
    advice_no = fields.Char('Advice No')
    sr_no = fields.Char('Serial No')
    message = fields.Char('Message')
    agents_irno = fields.Char('Agents IRNo')
    agency_irno = fields.Char('Agency IRNo')
    upload_batchno = fields.Char('Upload BatchNo')
    ho_non_ho = fields.Char('HO/NON-HO')
    domestic_international = fields.Char('Domestic/International')
    project_code = fields.Char('Project Code')
    tran_type = fields.Char('Transaction Type')
    isgec_emp_code = fields.Char('ISGEC EMP CODE')
    isgec_gstin = fields.Char('ISGEC GSTIN')
    supplier_name = fields.Char('Supplier Name')
    supplier_gstin = fields.Char('Supplier GSTIN')
    invoice_date = fields.Date('INVOICE DATE')
    pax_name = fields.Char('PAX NAME')
    sector = fields.Char('SECTOR')
    airline_name = fields.Char('Airline Name')
    travel_date = fields.Date('TRAVEL DATE')
    tkt_no = fields.Char('TKT No.')
    booked = fields.Char('BOOKED')
    service_charge = fields.Char('SERVICE CHARGE')
    igst_amt = fields.Float('IGST Amount.')
    sgst_amt = fields.Float('SGST Amount.')
    cgst_amt = fields.Float('CGST Amount.')
    total_service_amt = fields.Float('Total Service Amount.')
    total_ticket_amt = fields.Float('Total Ticket Amount.')
    total_amt = fields.Float('Total Amount')
    ref_no = fields.Char('REF NO')
    state_code = fields.Char('State Code')
    rcm_applicable = fields.Char('RCM Applicable')
    gst_tax_category = fields.Char('GST TAX Category')
    airline_gstin = fields.Char('Airline GSTIN')
    tkt_no_2 = fields.Char('TKT No.')
    booked_on = fields.Char('BOOKED ON')
    airline_name_2 = fields.Char('Airline Name')
    basic_fare = fields.Char('Basic Fare')
    yq_tax_amt = fields.Float('YQ Tax Amount.')
    isgt_amt_2 = fields.Float('IGST Amount.')
    sgst_amt_2 = fields.Float('SGST Amount.')
    cgst_amt_2 = fields.Float('CGST Amount.')
    all_other_taxes_amt = fields.Float('All Other Taxes Amount')
    total_ticket_amt_2 = fields.Float('Total Ticket Amount.')
    bta_btc = fields.Char('BTA/BTC')
    submission_period = fields.Char('Submission Period')
